language: cpp
compiler: gcc
sudo: require
service:
    - docker
git:
    depth: false
matrix:
  fast_finish: true

notifications:
    email:
      recipients:
      - gregory.voloir@epitech.eu
      - clement.beaubestre@epitech.eu
      - matthieu.sauer@epitech.eu
      - florian.lavabre@epitech.eu
      on_success: never
      on_failure: always

addons:
  sonarcloud:
    organization: "kaserta"
    token:
        secure:
stages:
    - build
    - tests
    - deploy

jobs:
    include :
        - stage: build
          name: "Build"
          if: branch = dev
          install:
            - docker pull epitechcontent/epitest-docker
          script:
            - docker run -v $PWD:/build epitechcontent/epitest-docker bash -c ""

        - stage: tests
          name: "Unitary Testing"
          if: branch = dev
          install:
            - docker pull epitechcontent/epitest-docker
          script:
            - docker run -v $PWD:/test epitechcontent/epitest-docker bash -c ""

        - stage: deploy
          name: "Deployement"
          if: branch = master AND type != cron
          before_script:
            - ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts
            - git checkout master
          script:
            - git push --repo git@git.epitech.eu:/clement.beaubestre@epitech.eu/NWP_myftp_2018 --force